export { ACCOUNT_MODULE_ID, accountSettingsDefaults } from '../../shared/account-settings'
import { ACCOUNT_MODULE_ID, accountSettingsDefaults } from '../../shared/account-settings'

export default defineNuxtPlugin(() => {
  contributeModule({
    id: ACCOUNT_MODULE_ID,
    parentId: 'auth',
    label: 'Conta e senha',
    description: 'Perfil, senha, 2FA e exclusão de conta.',
    icon: 'i-solar:user-circle-bold-duotone',
    routes: ['/account'],
    sidebarGroupId: 'auth',
    sidebarChildId: 'account',
    defaultEnabled: true,
    installable: false,
    order: 4,
  })

  contributeSidebarChild('auth', 'account', {
    label: 'Conta e senha',
    to: '/account',
    order: 4,
    when: 'auth',
    moduleId: ACCOUNT_MODULE_ID,
  })

  contributeModuleSettings({
    moduleId: ACCOUNT_MODULE_ID,
    groups: [
      {
        id: 'avatar',
        label: 'Imagem da conta',
        description: 'Formatos, tamanho e onde as imagens são armazenadas.',
        fields: [
          {
            key: 'imageExtensions',
            type: 'multiselect',
            label: 'Extensões permitidas',
            description: 'Tipos de arquivo aceitos no upload da imagem.',
            options: [
              { value: 'jpg', label: 'JPG' },
              { value: 'jpeg', label: 'JPEG' },
              { value: 'png', label: 'PNG' },
              { value: 'webp', label: 'WEBP' },
              { value: 'gif', label: 'GIF' },
            ],
            default: [...accountSettingsDefaults.imageExtensions],
          },
          {
            key: 'imageMaxSizeMb',
            type: 'number',
            label: 'Tamanho máximo',
            description: 'Limite do arquivo de imagem.',
            default: accountSettingsDefaults.imageMaxSizeMb,
            min: 0.5,
            max: 20,
            step: 0.5,
            unit: 'MB',
          },
          {
            key: 'imageStorageBackend',
            type: 'select',
            label: 'Armazenamento',
            description: 'Onde salvar a imagem de perfil. Seafile usa a conexão do módulo Painel → Seafile.',
            options: [
              { value: 'local', label: 'Local (pasta storage/)' },
              { value: 'seafile', label: 'Seafile' },
            ],
            default: accountSettingsDefaults.imageStorageBackend,
          },
          {
            key: 'imageLocalPath',
            type: 'text',
            label: 'Pasta local',
            description: 'Caminho relativo à raiz do projeto (criada automaticamente).',
            default: accountSettingsDefaults.imageLocalPath,
            placeholder: 'storage/avatars',
            enabledWhen: { key: 'imageStorageBackend', equals: 'local' },
          },
          {
            key: 'imageSeafilePath',
            type: 'text',
            label: 'Pasta na biblioteca',
            description: 'Subpasta na library Seafile onde os avatares serão salvos. Configure o servidor em Módulos → Seafile.',
            default: accountSettingsDefaults.imageSeafilePath,
            placeholder: '/avatars',
            enabledWhen: { key: 'imageStorageBackend', equals: 'seafile' },
          },
        ],
      },
      {
        id: 'username',
        label: 'Nome de usuário',
        fields: [
          {
            key: 'usernameAllowChange',
            type: 'boolean',
            label: 'Permitir alteração',
            description: 'Se desativado, o usuário não pode mudar o nome de usuário.',
            default: accountSettingsDefaults.usernameAllowChange,
          },
          {
            key: 'usernameMinLength',
            type: 'number',
            label: 'Mínimo de caracteres',
            default: accountSettingsDefaults.usernameMinLength,
            min: 1,
            max: 64,
            step: 1,
            row: 'username-length',
          },
          {
            key: 'usernameMaxLength',
            type: 'number',
            label: 'Máximo de caracteres',
            default: accountSettingsDefaults.usernameMaxLength,
            min: 1,
            max: 128,
            step: 1,
            row: 'username-length',
          },
          {
            key: 'usernameMaxChanges',
            type: 'number',
            label: 'Alterações permitidas',
            description: 'Quantas vezes o usuário pode alterar o nome no período.',
            default: accountSettingsDefaults.usernameMaxChanges,
            min: 1,
            max: 20,
            step: 1,
            enabledWhen: 'usernameAllowChange',
          },
          {
            key: 'usernameChangeIntervalDays',
            type: 'number',
            label: 'Intervalo entre alterações',
            description: 'Tempo mínimo entre uma alteração e outra.',
            default: accountSettingsDefaults.usernameChangeIntervalDays,
            min: 1,
            max: 3650,
            step: 1,
            unit: 'dias',
            enabledWhen: 'usernameAllowChange',
          },
        ],
      },
      {
        id: 'birthdate',
        label: 'Data de nascimento',
        fields: [
          {
            key: 'birthDateMinAge',
            type: 'number',
            label: 'Idade mínima',
            default: accountSettingsDefaults.birthDateMinAge,
            min: 1,
            max: 120,
            step: 1,
            unit: 'anos',
          },
        ],
      },
      {
        id: 'password',
        label: 'Senha',
        fields: [
          {
            key: 'passwordMinLength',
            type: 'number',
            label: 'Mínimo de caracteres',
            default: accountSettingsDefaults.passwordMinLength,
            min: 4,
            max: 256,
            step: 1,
            row: 'password-length',
          },
          {
            key: 'passwordMaxLength',
            type: 'number',
            label: 'Máximo de caracteres',
            default: accountSettingsDefaults.passwordMaxLength,
            min: 4,
            max: 512,
            step: 1,
            row: 'password-length',
          },
          {
            key: 'passwordRequireUppercase',
            type: 'boolean',
            label: 'Exigir letra maiúscula',
            default: accountSettingsDefaults.passwordRequireUppercase,
          },
          {
            key: 'passwordRequireLowercase',
            type: 'boolean',
            label: 'Exigir letra minúscula',
            default: accountSettingsDefaults.passwordRequireLowercase,
          },
          {
            key: 'passwordRequireNumber',
            type: 'boolean',
            label: 'Exigir número',
            default: accountSettingsDefaults.passwordRequireNumber,
          },
          {
            key: 'passwordRequireSpecial',
            type: 'boolean',
            label: 'Exigir caractere especial',
            description: 'Ex.: ! @ # $ % & *',
            default: accountSettingsDefaults.passwordRequireSpecial,
          },
        ],
      },
      {
        id: 'danger',
        label: 'Exclusão de conta',
        fields: [
          {
            key: 'allowAccountDeletion',
            type: 'boolean',
            label: 'Permitir exclusão da conta',
            description: 'Se desativado, a seção de exclusão não aparece para o usuário.',
            default: accountSettingsDefaults.allowAccountDeletion,
          },
        ],
      },
    ],
  })
})
